AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  HelloLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: java17
      Handler: teamfowler.testproject.GetPhotoByIdHandler
      MemorySize: 1024
      CodeUri: ./


  HelloLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join ['/', ['/aws/lambda', !Ref HelloLambdaFunction]]
      RetentionInDays: 30